Add item requests
DenisLeonenko93/java-shareit pull request #4
Opened 2023-07-06 16:29 UTC by DenisLeonenko93

2023-07-11 05:27 UTC, z8q requested changes

2023-07-11 05:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (hasOwner) {
Допускаются случаи, когда владелец отсутствует?

2023-07-11 05:27 UTC, z8q commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryIT.java
> +    private TestEntityManager entityManager;
Не используем?

2023-07-11 05:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/itemRequest/model/ItemRequest.java
> +    public int hashCode() {
Тут можно посмотреть примеры, когда в сущностях переопределяется hashcode и equals:
https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/
Вот этот абзац:
As you can see, Java’s default equals() and hashCode() methods only produce the required result if the Hibernate Session ensures that there is only 1 Java object that represents a specific record in the database table. If you load your entities in multiple Sessions or if you work with detached entities, you need to override these methods. In all other cases, it’s better to rely on Java’s default implementation.

Вот тут еще есть примеры по equals и hashcode, чуть подробнее
https://jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/

2023-07-11 05:27 UTC, z8q commented on src/test/java/ru/practicum/shareit/util/ExistValidAspectTest.java
> +package ru.practicum.shareit.util;
Вот этот блок из тз не нашел:
```
Реализовать тесты для работы с JSON для DTO в вашем приложении 
с помощью аннотации @JsonTest. 
Такие тесты имеют смысл в тех случаях, когда ваши DTO содержат в себе 
некоторую логику. Например, описание формата дат или валидацию. 
Выберите DTO, где есть подобные условия, и напишите тесты.
```

Кстати, формат дат можно определять через `@JsonFormat`

2023-07-11 05:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
>              "where (upper(i.name) like upper(concat('%', ?1, '%')) " +
like часто может в негативную сторону влиять на производительность запросов.
Вот тут описано:
https://use-the-index-luke.com/sql/where-clause/searching-for-ranges/like-performance-tuning
```
The opposite case is also possible: a LIKE expression that starts with a wild card. 
Such a LIKE expression cannot serve as an access predicate. 
The database has to scan the entire table if there are no other conditions 
that provide access predicates.
```

2023-07-11 06:57 UTC, DenisLeonenko93 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (hasOwner) {
Метод используется для двух случаев, если список бронирований запрашивает любой пользователь, то выдает список всех бронирований. Если пользователь хочет посмотреть бронирование всех его вещей, то hasOwner == true и выдает только список бронирования его вещей.

2023-07-11 18:53 UTC, DenisLeonenko93 commented on src/test/java/ru/practicum/shareit/util/ExistValidAspectTest.java
> +package ru.practicum.shareit.util;
Уточнял на QA. У меня нет изменений стандартного механизма сериализации/десериализации, поэтому наставник сказал необязательно писать тест на проверку стандартной библиотеки. Я пытался прикрутить `@JsonFormat`, но у меня все ломается, не могу с ним разобраться.

2023-07-11 19:18 UTC, DenisLeonenko93 commented on src/main/java/ru/practicum/shareit/itemRequest/model/ItemRequest.java
> +    public int hashCode() {
Еще в прошлом ТЗ переопределил эти методы. В статье вроде и написано, что необходимо использовать айди для equals. А hashCode допускается  возвращать одинаковый для всех объектов класса.

> The challenge here is that the hash code of your entity isn’t allowed to change after you added the object to a Set. So, you can’t use the primary key to calculate the hash code. You need to return a fixed value that’s the same for all objects of the entity class. That, of course, negatively affects the performance of very huge Sets and Maps because they put all objects into the same hash bucket. But Hibernate can’t efficiently manage huge associations anyways and you should avoid them in general.

2023-07-11 19:50 UTC, DenisLeonenko93 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
>              "where (upper(i.name) like upper(concat('%', ?1, '%')) " +
Если я правильно понял, то установив индекс для столбца, по которому происходит поиск, мы получим небольшое увеличение производительности, при больших объемах данных. Сделал индексацию.

2023-07-13 06:58 UTC, z8q commented on src/main/java/ru/practicum/shareit/itemRequest/model/ItemRequest.java
> +    public int hashCode() {
Прости, повторяюсь)
Там в конце делается вывод, что переопределять hashcode и equals имеет смысл только при использовании нескольких Hibernate сессий, либо если работаем с detached entities.
```
Detached - a detached instance is an object that has been persistent, but its Session has been closed. The reference to the object is still valid, of course, and the detached instance might even be modified in this state. A detached instance can be reattached to a new Session at a later point in time, making it (and all the modifications) persistent again. This feature enables a programming model for long running units of work that require user think-time. We call them application transactions, i.e., a unit of work from the point of view of the user.
```

В остальных случаях можно не переопределять

2023-07-13 07:02 UTC, z8q commented on src/test/java/ru/practicum/shareit/util/ExistValidAspectTest.java
> +package ru.practicum.shareit.util;
над полем с датой ставим что-то такое:
`@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss")`

2023-07-13 07:07 UTC, z8q approved these changes

2023-07-13 08:16 UTC, merged